### ISSUE TITLE
Question: Is it possible to record the sound at a higher volume (or to play it back at a higher volume)

### ISSUE THREAD

**Issue by serge-hulne** [Tougee/AudioRecorderView#13]
Question: 

Is it possible to record the sound at a higher volume (or to play it back at a higher volume)?

(By this I mean: programmatically (with code inside the app))

**Comment by Tougee** [comment]
It's just a View library, not concerned with the actual recording part.

I think the Android AudioRecord default uses full volume to recording, and you can control the playback volume by control you device or use `setVolume()` like APIs.

**Comment by serge-hulne** [comment]
Thank you very much.
C’est

**Comment by serge-hulne** [comment]
Thanks.
