### ISSUE TITLE
Appearance customization:

### ISSUE THREAD

**Issue by covenant3717** [Tougee/AudioRecorderView#3]
It would be very convenient to have the following parameters:

1) xml parameter to replace the microphone icon
2) xml-parameter for replacing the circle color of the microphone icon (at the moment of pressing)
3) xml-parameter to replace the color of the recording indicator (blinking dot)
4) xml parameter to replace button color stop recording
5) xml-parameter for replacing the text "Slide to cancel"
6) xml-parameter to replace the text "Cancel"

**Comment by Tougee** [comment]
I just open a PR related to this issue, feel free to review or give some advices :)

**Comment by covenant3717** [comment]
> I just open a PR related to this issue, feel free to review or give some advices :)

Is it possible to add a parameter for changing the activation / deactivation of the display of milliseconds in the record count?

Something like:
app: timer_milliseconds_active = "true" (by default "false")

counter view before activation: 00:00
counter view after activation: 00:00:00

**Comment by covenant3717** [comment]
answered in issue:)

чт, 5 нояб. 2020 г. в 12:18, Tougee <notifications@github.com>:

**Comment by Tougee** [comment]
Currently the time format logic is like below
``` kotlin
if (hours > 0)
        formatter.format("%d:%02d:%02d", hours, minutes, seconds).toString()
    else
        formatter.format("%02d:%02d", minutes, seconds).toString()
```
If support displays milliseconds, the time string may be a little long, what you think

**Comment by covenant3717** [comment]
> Currently the time format logic is like below
> 
> ```kotlin
> if (hours > 0)
>         formatter.format("%d:%02d:%02d", hours, minutes, seconds).toString()
>     else
>         formatter.format("%02d:%02d", minutes, seconds).toString()
> ```
> 
> If support displays milliseconds, the time string may be a little long, what you think

I do not think that someone will record a voice message for an entire hour, but if all such cases occur, then yes, the counter will be too long.
I think you are right and should be left as is.
I'm waiting for the merge of the current PR and the library update :)

**Comment by Tougee** [comment]
OK, I'll merge first and consider this later.

**Comment by Tougee** [comment]
Hi,
The new artifact of 1.0.2 can be downloaded, hope you enjoy.

There is also another problem with the display milliseconds you
proposed. If the value is too small, the animation will also be a
problem.For example, how often to refresh.
Can be considered later when free.


covenant3717 <notifications@github.com> 于2020年11月5日周四 下午3:33写道：

**Comment by covenant3717** [comment]
Once again I want to thank you for such a quick update :)

Regarding milliseconds, I imagined it something like this:

чт, 5 нояб. 2020 г. в 16:41, Tougee <notifications@github.com>:
