### ISSUE TITLE
parameters colors wrong

### ISSUE THREAD

**Issue by covenant3717** [Tougee/AudioRecorderView#6]
This "app: cancel_icon_color" colors the appearing circle of the microphone icon.

And this "app: circle_color" doesn't color anything.

**Comment by Tougee** [comment]
Got it, a typo in AudioRecordView.kt L107  :(

**Comment by covenant3717** [comment]
> Got it, a typo in AudioRecordView.kt L107 :(

It's okay, mistakes happen :)
