### ISSUE TITLE
Customizable microphone icon paddings

### ISSUE THREAD

**Issue by covenant3717** [Tougee/AudioRecorderView#7]
I would like to be able to customize the paddings of the microphone icon.
For example, here's a case: I need to align the "attachments" and "microphone" icons horizontally relative to each other.

![image](https://user-images.githubusercontent.com/44593466/98771025-18453000-2416-11eb-99ce-e7db1d7db940.png)
![image](https://user-images.githubusercontent.com/44593466/98771323-bf29cc00-2416-11eb-8707-a7f16600e604.png)

**Comment by Tougee** [comment]
You can use findViewById() and customize some details, like padding or gravity, etc.
```kotlin
 findViewById<View>(R.id.record_ib).setPadding(0, 0, 0 0)
```
