### ISSUE TITLE
Add options customize hints

### ISSUE THREAD

**Issue by covenant3717** [Tougee/AudioRecorderView#8]
Parameters for customizing the appearance of the container with a hint would be useful :)

Namely:
app: mic_hint_enable= "true" (default "false" and hint not showing)
app: mic_hint_color= "#000000"
app: mic_hint_text= "custom text"

![image](https://user-images.githubusercontent.com/44593466/98780246-16d03380-2427-11eb-84e4-ac505c24a0fb.png)

**Comment by Tougee** [comment]
```       
<attr name="mic_active_icon" format="reference" />
<attr name="mic_hint_enable" format="boolean" />
<attr name="mic_hint_color" format="color" />
<attr name="mic_hint_bg" format="reference" />
<attr name="mic_hint_text" format="string" />
```
micHintEnable  (default true)
If the micHintEnable set to false, the vibrationEnable will be ignored.
